version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama_graphrag_1 
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama # Connects the volume to the container
    restart: unless-stopped

  neo4j:
    image: neo4j:latest
    container_name: neo4j_graphrag_1
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt Protocol
    volumes:
      - neo4j_data:/data # Creates a new volume for the Neo4j database
    environment:
      - NEO4J_AUTH=neo4j/test1234 # CHANGE THIS PASSWORD
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    restart: unless-stopped

volumes:
  ollama:
    external: true 
  neo4j_data: 

  